version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: Vanaheim:1:1,Helheim:1:1,Kryptonopolis:2:1:compact,Monitor:2:1,ElasticSearch:1:1,SentenceEncoder:1:1,PushEvent:1:1,DeleteMonitor:1:1,DeleteKryptonopolis:1:1
      FAKE_KRYPTO_URL: http://kafka-docker:3000
      KAFKA_MESSAGE_MAX_BYTES: "15728640"
      KAFKA_REPLICA_FETCH_MAX_BYTES: "15728640"
    depends_on:
      - zookeeper
